import type { FileItem, Provider, Channel } from "./types";

export const mockProviders: Provider[] = [
  { id: "drive", name: "Google Drive", icon: "🗂️", status: "unlinked" },
  { id: "dropbox", name: "Dropbox", icon: "📦", status: "unlinked" },
  { id: "onedrive", name: "OneDrive", icon: "☁️", status: "unlinked" },
  { id: "notion", name: "Notion", icon: "📝", status: "unlinked" },
  { id: "github", name: "GitHub", icon: "🐙", status: "unlinked" },
];

export const mockChannels: Channel[] = [
  {
    id: "eng",
    name: "Engineering",
    subgroups: [
      { id: "frontend", name: "Frontend Team", fileCount: 24 },
      { id: "backend", name: "Backend Team", fileCount: 31 },
      { id: "devops", name: "DevOps", fileCount: 18 },
    ],
  },
  {
    id: "design",
    name: "Design",
    subgroups: [
      { id: "ui", name: "UI Design", fileCount: 42 },
      { id: "ux", name: "UX Research", fileCount: 15 },
      { id: "brand", name: "Brand", fileCount: 8 },
    ],
  },
  {
    id: "product",
    name: "Product",
    subgroups: [
      { id: "roadmap", name: "Roadmap", fileCount: 12 },
      { id: "specs", name: "Specifications", fileCount: 28 },
      { id: "analytics", name: "Analytics", fileCount: 19 },
    ],
  },
  {
    id: "marketing",
    name: "Marketing",
    subgroups: [
      { id: "content", name: "Content", fileCount: 35 },
      { id: "social", name: "Social Media", fileCount: 22 },
      { id: "campaigns", name: "Campaigns", fileCount: 17 },
    ],
  },
];

export const mockFiles: FileItem[] = [
  {
    id: "1",
    title: "Q4 Product Roadmap",
    type: "doc",
    source: "drive",
    channel: "Product",
    subgroup: "Roadmap",
    tags: ["roadmap", "q4", "planning"],
    modifiedDate: "2025-10-03",
    size: "2.4 MB",
    locations: ["Product/Roadmap/Q4 Planning", "Shared Drives/Company"],
    versions: 12,
    contentHash: "a3f9d8e2",
  },
  {
    id: "2",
    title: "Design System Components",
    type: "presentation",
    source: "notion",
    channel: "Design",
    subgroup: "UI Design",
    tags: ["design-system", "components", "ui"],
    modifiedDate: "2025-10-04",
    size: "8.1 MB",
    locations: ["Design/UI Design/Systems"],
    versions: 5,
    contentHash: "b7c2d1a4",
  },
  {
    id: "3",
    title: "API Documentation v2.3",
    type: "doc",
    source: "github",
    channel: "Engineering",
    subgroup: "Backend Team",
    tags: ["api", "docs", "backend"],
    modifiedDate: "2025-10-05",
    size: "1.2 MB",
    locations: ["Engineering/Backend/Docs", "GitHub/main/docs"],
    versions: 23,
    contentHash: "c9e4f2b1",
  },
  {
    id: "4",
    title: "User Research Findings",
    type: "pdf",
    source: "drive",
    channel: "Design",
    subgroup: "UX Research",
    tags: ["research", "ux", "user-testing"],
    modifiedDate: "2025-10-02",
    size: "5.7 MB",
    locations: ["Design/UX Research/October"],
    versions: 3,
    contentHash: "d1a8c3e7",
  },
  {
    id: "5",
    title: "Infrastructure Setup Guide",
    type: "doc",
    source: "notion",
    channel: "Engineering",
    subgroup: "DevOps",
    tags: ["devops", "infrastructure", "setup"],
    modifiedDate: "2025-09-28",
    size: "3.2 MB",
    locations: ["Engineering/DevOps/Guides"],
    versions: 8,
    contentHash: "e5b9d2c4",
  },
  {
    id: "6",
    title: "Brand Guidelines 2025",
    type: "pdf",
    source: "dropbox",
    channel: "Design",
    subgroup: "Brand",
    tags: ["brand", "guidelines", "style"],
    modifiedDate: "2025-10-01",
    size: "12.3 MB",
    locations: ["Design/Brand/Guidelines", "Shared/Brand Assets"],
    versions: 4,
    contentHash: "f2c7a1d8",
  },
  {
    id: "7",
    title: "Social Media Calendar",
    type: "sheet",
    source: "drive",
    channel: "Marketing",
    subgroup: "Social Media",
    tags: ["social", "calendar", "planning"],
    modifiedDate: "2025-10-05",
    size: "890 KB",
    locations: ["Marketing/Social/Planning"],
    versions: 15,
    contentHash: "a8d3c2e1",
  },
  {
    id: "8",
    title: "Product Spec: New Dashboard",
    type: "doc",
    source: "notion",
    channel: "Product",
    subgroup: "Specifications",
    tags: ["spec", "dashboard", "feature"],
    modifiedDate: "2025-10-04",
    size: "2.1 MB",
    locations: ["Product/Specs/Dashboard"],
    versions: 7,
    contentHash: "b9e1d4c2",
  },
  {
    id: "9",
    title: "Frontend Architecture Diagram",
    type: "image",
    source: "drive",
    channel: "Engineering",
    subgroup: "Frontend Team",
    tags: ["architecture", "diagram", "frontend"],
    modifiedDate: "2025-09-30",
    size: "1.8 MB",
    locations: ["Engineering/Frontend/Docs"],
    versions: 6,
    contentHash: "c2a7e3d1",
  },
  {
    id: "10",
    title: "Campaign Performance Report",
    type: "sheet",
    source: "drive",
    channel: "Marketing",
    subgroup: "Campaigns",
    tags: ["campaign", "analytics", "report"],
    modifiedDate: "2025-10-03",
    size: "1.5 MB",
    locations: ["Marketing/Campaigns/Reports"],
    versions: 9,
    contentHash: "d7c2e1a4",
  },
  {
    id: "11",
    title: "Analytics Dashboard Config",
    type: "code",
    source: "github",
    channel: "Product",
    subgroup: "Analytics",
    tags: ["analytics", "config", "dashboard"],
    modifiedDate: "2025-10-05",
    size: "124 KB",
    locations: ["Product/Analytics/Config", "GitHub/analytics-dashboard"],
    versions: 18,
    contentHash: "e3d1c4a2",
  },
  {
    id: "12",
    title: "Content Strategy Q4",
    type: "doc",
    source: "notion",
    channel: "Marketing",
    subgroup: "Content",
    tags: ["content", "strategy", "q4"],
    modifiedDate: "2025-10-02",
    size: "2.8 MB",
    locations: ["Marketing/Content/Strategy"],
    versions: 11,
    contentHash: "f1a8d2c3",
  },
];
